# Generated by Django 6.0.5 on 2026-05-14 15:08

import django.db.models.deletion
import pinmok.content.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('type', models.CharField(choices=[('article', 'Article'), ('page', 'Page')], default='article', max_length=20, verbose_name='type')),
                ('template', models.CharField(blank=True, default=pinmok.content.enums.TemplateAction['ARTICLE'], max_length=255, verbose_name='template')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('published', 'Published'), ('retracted', 'Retracted'), ('deleted', 'Deleted')], default='draft', max_length=20, verbose_name='status')),
                ('sort_order', models.PositiveIntegerField(default=10000, verbose_name='sort order')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='extra')),
                ('is_top', models.BooleanField(default=False, verbose_name='is top')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='recommended')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
                'permissions': [('write_article', 'Can write article'), ('publish_article', 'Can publish article')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.article',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover image')),
                ('template', models.CharField(blank=True, default=pinmok.content.enums.TemplateAction['LIST'], max_length=255, verbose_name='template')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=10000, verbose_name='sort order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.category', verbose_name='categories'),
        ),
        migrations.CreateModel(
            name='ArticleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('gallery', 'Gallery'), ('attachment', 'Attachment'), ('video', 'Video'), ('audio', 'Audio')], max_length=20, verbose_name='usage')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='alternative text')),
                ('sort_order', models.PositiveIntegerField(default=10000, verbose_name='sort order')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_resources', to='content.article', verbose_name='article')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_resources', to='padmin.resource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'article resource',
                'verbose_name_plural': 'article resources',
                'ordering': ['sort_order'],
                'unique_together': {('article', 'resource', 'usage')},
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('ja', '日本語'), ('ar', 'العربيّة')], db_index=True, default='zh-hans', help_text='Which language this translation belongs to.', max_length=10, verbose_name='language')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='subtitle')),
                ('summary', models.TextField(blank=True, default='', verbose_name='summary')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'article translation',
                'verbose_name_plural': 'article translations',
                'constraints': [models.UniqueConstraint(fields=('article', 'language'), name='uniq_article_language')],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('ja', '日本語'), ('ar', 'العربيّة')], db_index=True, default='zh-hans', help_text='Which language this translation belongs to.', max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'category translation',
                'verbose_name_plural': 'category translations',
                'constraints': [models.UniqueConstraint(fields=('category', 'language'), name='uniq_category_language')],
            },
        ),
    ]
