[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pinmok-content"
version = "1.0.1"
description = "Pinmok content module"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "惠达浪", email = "crazys@126.com" }]
requires-python = ">=3.12"
dependencies = ["django>=5.2", "pinmok>=1.0"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Django",
    "Framework :: Django :: 5",
    "Framework :: Django :: 6",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
]

[project.urls]
Source = "https://github.com/pinmok/pinmok"

[tool.setuptools.packages.find]
where = ["."]
include = ["pinmok.content*"]

[tool.setuptools.exclude-package-data]
"*" = [
    "**/__pycache__/*",
    "**/*.pyc",
]
