[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Pinmok content"
version = "1.0.0"
description = "Pinmok content module"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "惠达浪", email = "crazys@126.com" }]
requires-python = ">=3.11"
dependencies = ["django>=5.0", "pinmok>=1.0"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Framework :: Django",
    "Framework :: Django :: 5",
    "Framework :: Django :: 6",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
]

[tool.setuptools]
packages = ["pinmok.content"]
